### ISSUE TITLE
source command bashism fails to load environment 

### ISSUE THREAD

**Issue by rhass** [chef-cookbooks/omnibus#141]
The method `execute_with_omnibus_toolchain` attempts to load the environment, however fails as the `execute` resource invokes a bourne shell opposed to a bash shell.

https://github.com/chef-cookbooks/omnibus/blob/master/libraries/omnibus_build.rb#L136

The following scripts illustrates what is happening:

``` shell
#!/usr/bin/env bash
# This file should be named /tmp/test-env.sh 
export FOO='bar'
```

``` shell
#!/usr/bin/env sh

echo "Sourcing test environment file..."
source /tmp/test-env.sh

echo "FOO is set to: $FOO"
```
Running this results in the following:
``` shell
# chmod +x /tmp/test.sh
/tmp/test.sh
Sourcing test environment file...
/tmp/test.sh: 4: /tmp/test.sh: source: not found
FOO is set to: 
```

However, when changing either the parent shell to `bash` or using `.` instead of `source` the error is resolved.

I have been working on a fix for this, however I am currently encountering a different error which is unclear to me at this time if it is caused by my fix or if there is another bug elsewhere which is now being exposed as result of my fix.

**Comment by rhass** [comment]
In the interest of transparency and communal debugging, the new error to which I am referring can be seen in the following gist: https://gist.github.com/rhass/2c012c7f4d035b0a7492

**Comment by schisamo** [comment]
WRT to the `source` vs `.`...I'm surprised the `omnibus_build` integration tests have been passing (they are automatically run on every PR). The fixture recipe is:
https://github.com/chef-cookbooks/omnibus/blob/master/test/fixtures/cookbooks/omnibus_build/recipes/execute.rb

Your second error appears to be related to Ruby environments bleeding into each other. That's based on this output: 

```
D | You are trying to install in deployment mode after changing
D | your Gemfile. Run `bundle install` elsewhere and add the
D | updated Gemfile.lock to version control.
```

I find that output weird as the `chef` software definition calls a normal `bundle install` vs a `bundle install --deployment`:
https://github.com/chef/omnibus-software/blob/master/config/software/chef.rb#L62

Could you try setting the following attribute on your `omnibus_build` resource:

```ruby
environment(
  '_ORIGINAL_GEM_PATH' => '',
  'GEM_PATH' => '',
  'GEM_HOME' => '',
  'GEM_ROOT' => '',
  'BUNDLE_BIN_PATH' => '',
  'BUNDLE_GEMFILE' => '',
  'RUBYLIB' => '',
  'RUBYOPT' => '',
  'RUBY_ENGINE' => '',
  'RUBY_ROOT' => '',
  'RUBY_VERSION' => '',
)
```

If that fixes the issue we'll need to port this helper over from the `languages` cookbook:
https://github.com/chef-cookbooks/languages/blob/master/libraries/_helper.rb#L53-L86

It would be used to wrap the actual `execute` resource which runs the omnibus build like this:
https://github.com/chef-cookbooks/languages/blob/master/libraries/language_execute.rb#L48-L58

**Comment by rhass** [comment]
The environment override didn't seem to fix the isssue: https://gist.github.com/rhass/5af1da2dbc50a797434c

Disclaimer, the log will reflect some additional changes I have made to the omnibus-cookbook:
https://github.com/chef-cookbooks/omnibus/compare/master...rhass:debugging

My wrapper for omnibus-chef is here: https://github.com/rhass/omnibus-chef-arm/

I  will try to dig into this a little more this weekend and see if I can find anything else that stands out, and if I do I will also try to update the tests to fail correctly.

**Comment by rhass-r7** [comment]
I did some tinkering over the weekend and was able to cause other breakages with some of the things I tried out. For example, I changed the `load-omnibus-toolchain.sh` script to have an `exec "${@}"` at the end, along with the `execute_with_omnibus_toolchain` to pass command through the script; sorta worked -- but broke differently. I also forced the PATH variable with the environment overrides, which also sorta worked, but also broke differently.

This being said, I have been testing with the angrychef project in omnibus-chef -- which raises the question, Is there anything special about the angrychef build which may be giving me grief?

**Comment by schisamo** [comment]
@rhass-r7 Not that I can think of. I'll be putting this resource through some real world paces over the next few weeks (for building delivery-cli). Hopefully I'll hit some of the same issues.

**Comment by rhass** [comment]
Thanks, I will see if I can reproduce the issue with the delivery-cli
project as well.

**Comment by rhass** [comment]
It looks like the delivery-cli has a cookbook dependency which is internal to chef at the moment (artifactory-pro).

```
rhass@verhaeghe:~/src/delivery-cli/omnibus-delivery-cli$ berks
/home/rhass/.chefdk/gem/ruby/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/webagent-cookie.rb:458: warning: already initialized constant HTTPClient::CookieManager
/home/rhass/.chefdk/gem/ruby/2.1.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:8: warning: previous definition of CookieManager was here
Resolving cookbook dependencies...
Fetching 'delivery_rust' from source at ../cookbooks/delivery_rust
Fetching 'artifactory-pro' from git@github.com:chef-cookbooks/artifactory-pro.git (at master)
Git error: command `git clone git@github.com:chef-cookbooks/artifactory-pro.git "/home/rhass/.berkshelf/.cache/git/2ba1f89df7500a23e774f63ffac93af4248f6927" --bare --no-hardlinks` failed. If this error persists, try removing the cache directory at '/home/rhass/.berkshelf/.cache/git/2ba1f89df7500a23e774f63ffac93af4248f6927'.Output from the command:

Cloning into bare repository '/home/rhass/.berkshelf/.cache/git/2ba1f89df7500a23e774f63ffac93af4248f6927'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Not sure if this is going to matter for my reproduction use case, but I wanted to let you know for now. I will see if I can work around it and follow up.

**Comment by rhass** [comment]
Interested development today. On Ubuntu 12.04 I was able to set the following to get a successful build:

```ruby
  environment({
    'HOME' => build_user_home
  })
```

I need to try other platforms to ensure this resolved the issue, as well as backout one of my debugging hacks to make sure that is the only variable at play here -- but I wanted to share this information. I think the bashism stuff will still need to be landed, and I will make a separate PR for any other required changes.
